### ISSUE TITLE
Special characters.

### ISSUE THREAD

**Issue by ibnuda** [xyncro/freya-routers#1]
Hello, I have found some problem when I use freya-routers.

In the following program,
```
let captorname =
  freya {
    let! name = Route.atom_ "name" |> Freya.Optic.get
    return
      match name with
      | Some name -> name
      | None -> "world"
  }

let handlerhello =
  freya {
    let! name = captorname
    return sprintf "Hello %s" name |> Represent.text
  }

let routehello =
  freyaMachine {
    handleOk handlerhello
  }
let routelist =
  freyaRouter {
    resource "/hello{/name}" routehello
  }
```
What am I doing : 
- request (GET) `/hello/wo%20rld`
- request (GET) `/hello/wo%2Frld`

Expected result : 
- `Hello wo rld`
- `Hello wo/rld`

What I've got : 
- Empty response
- `Hello wo/rld`

My question : 
- Is this the expected result when I have `space` reserved character while I got the expected result of `/` just fine?

**Comment by kolektiv** [comment]
Hi, sorry for a slow response. The OWIN standard has an unfortunate implementation detail which encodes/decodes paths before they get to the OWIN handlers. This makes routing using nothing but OWIN compatible code inaccurate. However, if you're using Kestrel or Katana based servers, there's a workaround - a Freya polyfill. This might well be the answer for you!

See if https://docs.freya.io/en/latest/reference/polyfills/index.html (and the appropriate polyfill) works for you!

**Comment by ibnuda** [comment]
Thanks, it works on dotnetcore.

Request to `http://localhost:8083/hello/wor%23ld` responded with `Hello wor#ld` and request to `http://localhost:8083/hello/wor%20ld` responded with `Hello wor ld`.

All I have to do is just change this code.
```
let routes = UriTemplateRouter.Freya routelist
let midfunc = OwinMidFunc.ofFreya routes
```
to this
```
let routes = UriTemplateRouter.Freya routelist
let pipelineroutes = Polyfill.kestrel >?= routes
let midfunc = OwinMidFunc.ofFreya pipelineroutes
```
and add Freya.Polyfills.Kestrel as one of dependencies. Though I have to downgrade `Microsoft.AspNetCore.Server.Kestrel` from `1.1.0` to `1.0.0`.

Thanks.
